// <auto-generated />
namespace registrationLogin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class lastName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lastName));
        
        string IMigrationMetadata.Id
        {
            get { return "201803271602348_lastName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
